#!/bin/sh

start() {
  echo -n "Starting webconn daemon: "
  chgrp dialout /dev/ttyS1
  start-stop-daemon -S -m -b -q -p /var/run/webconn.pid --exec /webconn/bin/launcher
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
  echo -n "Stopping webconn daemon: "
  start-stop-daemon -K -q -p /var/run/webconn.pid
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
  stop
  sleep 1
  start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?

