# Machine support

obj-y += nxp2120.o
obj-y += lldebug.o
obj-y += irq.o
obj-y += timer.o

obj-y += nx_adc.o
obj-y += nx_alive.o
obj-y += nx_audio.o
obj-y += nx_spdif.o
obj-y += nx_clkpwr.o
obj-y += nx_csc.o
obj-y += nx_deinterlace.o
obj-y += nx_dma.o
obj-y += nx_dpc.o
obj-y += nx_ecid.o
obj-y += nx_ehci.o
obj-y += nx_gpio.o
obj-y += nx_i2c.o
obj-y += nx_intc.o
obj-y += nx_mcud.o
obj-y += nx_mcus.o
obj-y += nx_mlc.o
obj-y += nx_mpegtsif.o
obj-y += nx_ohci.o
obj-y += nx_ppm.o
obj-y += nx_pwm.o
obj-y += nx_rotator.o
obj-y += nx_rtc.o
obj-y += nx_scaler.o
obj-y += nx_sdhc.o
obj-y += nx_sspspi.o
obj-y += nx_timer.o
obj-y += nx_uart.o
obj-y += nx_udc.o
obj-y += nx_vip.o
obj-y += Turnaround_linux.o

obj-y += adc.o
obj-y += dma.o
obj-y += gpio.o
obj-y += init.o
obj-y += pwm.o
obj-y += sys.o	
obj-y += wdt.o	

obj-y += board.o
obj-y += cpu_device.o
obj-y += board_device.o

obj-$(CONFIG_PM) 				+= pm.o sleep.o

obj-$(CONFIG_MACH_WEBCON)		+= mach-webcon.o

